- name: Checkout
        uses: actions/checkout@v3

      # Adicione este bloco de debug
      - name: Debug Secrets
        run: |
          echo "Verificando se as chaves existem:"
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "ERRO: ACCESS_KEY esta vazia"; else echo "OK: ACCESS_KEY encontrada"; fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then echo "ERRO: SECRET_KEY esta vazia"; else echo "OK: SECRET_KEY encontrada"; fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2